name: ReorderPictures

on:
  workflow_dispatch:
    inputs:
      product_id: { description: "Ürün ID",   required: true }
      src_pos:    { description: "Görsel sıra", required: true }

jobs:
  reorder:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome:125.0
        options: >-
          --shm-size 2g        # büyük shared-mem, OTA yüklemeler için

    steps:
      - uses: actions/checkout@v4          # ← artık host’ta

      - name: Set up Python
        uses: actions/setup-python@v5
        with: { python-version: "3.12", cache: "pip" }

      - name: Install deps
        run: pip install selenium

      - name: Run script (remote webdriver)
        env:
          SELENIUM_REMOTE_URL: "http://localhost:4444/wd/hub"
        run: |
          python reorder_pictures.py \
            --product-id ${{ github.event.inputs.product_id }} \
            --src-pos    ${{ github.event.inputs.src_pos }}

