name: ReorderPictures

on:
  workflow_dispatch:
    inputs:
      batch:
        description: "productId:srcPos,productId:srcPos ..."
        required: true

jobs:
  reorder:
    runs-on: ubuntu-latest
    container: selenium/standalone-chrome:125.0   # Chrome hazır, hızlı!

    steps:
      - uses: actions/checkout@v4

      - name: Install Python & deps
        run: |
          apt-get update -qq
          apt-get install -y python3 python3-pip
          pip install selenium

      - name: Run batch script
        env:
          SELENIUM_REMOTE_URL: http://localhost:4444/wd/hub
        run: |
          python reorder_pictures.py --batch "${{ github.event.inputs.batch }}"
