name: Python Script Runner

on:
  workflow_dispatch:
    inputs:
      batch:
        description: 'Batch parameter (e.g., "231321:2,235412:5")'
        required: true
        type: string

jobs:
  run-script:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: |
        pip install selenium
        
    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser
        
    - name: Run reorder script
      run: |
        python reorder_pictures.py --batch "${{ github.event.inputs.batch }}"
