name: ReorderPictures

on:
  workflow_dispatch:
    inputs:
      product_id: { description: "Ürün ID",   required: true }
      src_pos:    { description: "Görsel sıra", required: true }

jobs:
  reorder:
    runs-on: ubuntu-latest

    # ★ Workflow’un tamamı bu imajda döner
    container: selenium/standalone-chrome:125.0     # versiyon sabitleyebilirsiniz

    steps:
      - uses: actions/checkout@v4

      - name: Install Python & deps      # Chrome zaten var ➜ sadece Python
        run: |
          apt-get update -qq
          apt-get install -y python3 python3-pip
          pip install selenium

      - name: Run script
        run: |
          python reorder_pictures.py \
            --product-id ${{ github.event.inputs.product_id }} \
            --src-pos    ${{ github.event.inputs.src_pos }}
